new_shop/djvenv/guitar_shop/goods/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'goods'

urlpatterns = [path('', views.main_page, name='main_page'),
               path('catalog/<slug:slug>', views.catalog_details, name='catalog_details'),
               path('instruments/<slug:slug>', views.catalog_details_instruments, name='catalog_details_instruments')
               ]

new_shop/djvenv/guitar_shop/guitar_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings # подтягиваем settings
from django.conf.urls.static import static
#from . import views    # импорт представлений из приложения goods

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls', namespace='goods')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#accounts/login/ [name='login']+
#accounts/logout/ [name='logout']+
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

new_shop/djvenv/guitar_shop/goods/models.py
from django.db import models

class CategoryGoods(models.Model): # в моделе харянятся категории товаров

    category = models.CharField(max_length=50)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return self.category

class AllGoods(models.Model): # модель которая более подробно описывает товары в магазине так же есть индексация

    #-----------------------------------------------------------------------------------------------#
    #сюда возможно добавлю контекснтый менеджер для того что бы отключать товары которые отсутствуют#
    #-----------------------------------------------------------------------------------------------#

    all_goods = models.CharField(max_length=50)
    slug = models.SlugField(max_length=250, unique=True)
    availability = models.BooleanField(null=True)
    quantity = models.IntegerField()
    image = models.ImageField( upload_to='images/', null=True, default='no_photo.png')
    price = models.IntegerField()
    model_of_instrument = models.CharField(max_length=50, null=True)
    articul = models.CharField(max_length=15, null=True, unique=True)

    category_goods = models.ForeignKey(CategoryGoods, on_delete=models.CASCADE, related_name= 'goods_all')

    def save(self, *args, **kwargs):    # метод для валидации полей которые могут принять отрицательные значения
        if self.quantity < 0:
            raise ValueError('Количество не может быть отрицательным')
        if self.price < 0:
            raise ValueError('Цена не может быть отрицательной')
        super().save(*args, **kwargs)

    class Meta:

        ordering = ['-price']
        indexes =[models.Index(fields=['-price']), ]

    def __str__(self):
        return self.all_goods

class СharacteristicsOfInstruments(models.Model):
    # для гитары
    color = models.CharField(max_length=50, null=True)
    construction = models.CharField(max_length=50, null=True)
    soundboard = models.CharField(max_length=50, null=True)
    guitar_neck = models.CharField(max_length=50, null=True)
    fingerboard = models.IntegerField(null=True)
    guitar_scale = models.CharField(max_length=50, null=True)
    frets = models.IntegerField(null=True)
    pickups = models.CharField(max_length=50, null=True)
    color_accessories = models.CharField(max_length=50, null=True)
    guitar_bridge = models.CharField(max_length=50, null=True)
    pegs = models.CharField(max_length=50, null=True)
    year_release = models.IntegerField(null=True)
    country_release =  models.CharField(max_length=50, null=True)
    # для звукоснимателей
    guitar_pickup_type = models.CharField(max_length=50, null=True)
    size = models.CharField(max_length=50, null=True)
    resistance = models.CharField(max_length=50, null=True)
    # для усилителей
    built_in_effects = models.CharField(max_length=50, null=True)
    number_of_channels = models.IntegerField(null=True)
    effect_loop = models.CharField(max_length=50, null=True)
    headphone_output = models.CharField(max_length=50, null=True)
    combo_amplifier_type = models.IntegerField(null=True)
    number_of_speakers = models.CharField(max_length=50, null=True)
    # для процессоров и педалей
    effect_loop = models.CharField(max_length=50, null=True)
    expression_pedal = models.CharField(max_length=50, null=True)
    digital_interfaces = models.CharField(max_length=50, null=True)
    effect_type = models.CharField(max_length=50, null=True)
    # для комплектущих
    number_of_strings_in_the_setcombo_amplifier_type = models.IntegerField(null=True)
    tension = models.CharField(max_length=50, null=True)
    core = models.CharField(max_length=50, null=True)
    material = models.CharField(max_length=50, null=True)

    describtion = models.TextField(null=True)
    all_goods = models.ForeignKey(AllGoods, on_delete=models.CASCADE, related_name = 'describe')

new_shop/djvenv/guitar_shop/goods/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

#goods_all - это related_name
def main_page(request):
    all_categories = CategoryGoods.objects.all()    # выводит список доступных видов товаров на главной странице
    return render(request, 'goods/catalog_of_goods.html', {'all_categories':all_categories})

def catalog_details(request, slug):
    # ------------------------------#
    # Добавить постраничную разбивку#
    # ------------------------------#
    insruments_catalog = get_object_or_404(CategoryGoods, slug=slug)
    product_sections = insruments_catalog.goods_all.all()
    return render(request, 'goods/catalog_details.html', {'product_sections':product_sections})

def catalog_details_instruments(request, slug):
    # ------------------------------#
    # Добавить постраничную разбивку#
    # ------------------------------#
    instrument = AllGoods.objects.filter(slug=slug)

    get_instrument = get_object_or_404(AllGoods, slug=slug)
    describtion = get_instrument.describe.all()
    return render(request, 'goods/catalog_details_instruments.html', {'instrument':instrument, 'describtion':describtion})



    

new_shop/djvenv/guitar_shop/templates/goods/catalog_details.html
{% extends 'base.html' %}

{% block title %}Каталог товаров{% endblock %}

{% block content %}
<div class="catalog_details">

<ul >
    {% for i in product_sections %}
    <li style="display: inline-block">
        <ul>
            <li>{{i.image}}</li>
            <li><a href="{% url 'goods:catalog_details_instruments' i.slug %}">{{ i.all_goods }} {{ i.model_of_instrument }}</a></li>
            <li><strong>Цена:</strong>{{ i.price }}</li>
        </ul>
    </li>
    {% endfor %}
</ul>

</div>
{% endblock %}

new_shop/djvenv/guitar_shop/templates/goods/catalog_details_instruments.html
{% extends 'base.html' %}

{% block title %}Каталог товаров{% endblock %}

{% block content %}
<div class="catalog_details_instruments">
<ul>
    {% for i in instrument %}
            <li>{{i.image}}</li>
            <li>  {{ i.all_goods }} {{ i.model_of_instrument }}</li>
            <li><strong>Цена: </strong>{{ i.price }}</li>
    {% endfor %}

    {% for i in describtion %}
        <li><strong>Количество каналов: </strong>{{i.number_of_channels}}</li>
        <li><strong>Тип усилителя: </strong>{{ i.combo_amplifier_type }}</li>
        <li><strong>Встроенные эффекты: </strong>{{ i.built_in_effects }}</li>
        <li><strong>Петля эффектов: </strong>{{ i.effect_loop }}</li>
        <li><strong>Выход на наушники: </strong>{{ i.headphone_output }}</li>
        <li><strong>Количество динамиков: </strong>{{ i.number_of_speakers }}</li>


    {% endfor %}
</ul>
</div>
{% endblock %}

new_shop/djvenv/guitar_shop/templates/goods/catalog_of_goods.html
{% extends 'base.html' %}
{% block content %}

<div class="catalog_of_goods">
    <ul >
    {% for i in all_categories %}

        <li><a href="{% url 'goods:catalog_details' i.slug %}"> {{i.category}} </a></li>

    {% endfor %}
    </ul>

</div>
<div>
    <p class="about">
    Добро пожаловать! Наш интернет-магазин предоставляет широкий ассортимент электро- и бас-гитар, и обеспечивает быструю и недорогую доставку
    по всей территории России. Все инструменты прошли полную отстройку и предпродажную подготовку, снабжены свежими струнами
    и полностью готовы стать вашими верными спутниками.
    <p>
</div>
{% endblock %}